<div class="rowElem">
    <label>{% trans 'Nom d\'utilisateur non existant' %}:</label>
    <div class="formRight">
        <input type="text" name="username" placeholder="{% trans 'Entrez un nom d\'utilisateur' %}" required="true" />
    </div>
	<label>{% trans 'Mot de passe' %}:</label>
    <div class="formRight">
        <input type="text" name="password" placeholder="{% trans 'Entrez un mot de passe d\'au moins 4 caractères' %}" required="true" />
    </div>
    <div class="fix"></div>
</div>
