{% extends "layout_default.phtml" %}
{% set active_menu = 'system' %}

{% block breadcrumbs %}
<ul>
    <li class="firstB"><a href="{{ '/'|alink }}">{% trans 'Home' %}</a></li>
    <li><a href="{{ 'serviceyunohostshared'|alink }}">{% trans 'YunoHost Shared servers' %}</a></li>
    <li class="lastB">{{ server.name }}</li>
</ul>
{% endblock %}

{% block content %}
<div class="widget">
    <div class="head">
        <h5>Server management</h5>
    </div>

	<form method="post" action="{{ 'api/admin/serviceyunohostshared/server_update'|link }}" id="server-update" class="mainForm save api-form" data-api-msg="Server updated">
                <fieldset>
                    <div class="rowElem noborder">
                        <label>{% trans 'Name' %}:</label>
                        <div class="formRight">
                            <input type="text" name="name" value="{{ server.name }}" required="required" placeholder="{% trans 'Unique name to identify this server' %}">
                        </div>
                        <div class="fix"></div>
                    </div>
					<div class="rowElem">
                        <label>{% trans 'Group' %}:</label>
                        <div class="formRight">
                            <input type="text" name="group" value="{{ server.group }}" placeholder="{% trans 'Server group' %}">
                        </div>
                        <div class="fix"></div>
                    </div>
					<div class="rowElem">
                        <label>{% trans 'IPv4' %}:</label>
                        <div class="formRight">
                            <input type="text" name="ipv4" value="{{ server.ipv4 }}" placeholder="{% trans 'IPv4 address of the server' %}">
                        </div>
                        <div class="fix"></div>
                    </div>
					<div class="rowElem">
                        <label>{% trans 'IPv6' %}:</label>
                        <div class="formRight">
                            <input type="text" name="ipv6" value="{{ server.ipv6 }}" placeholder="{% trans 'IPv6 address of the server' %}">
                        </div>
                        <div class="fix"></div>
                    </div>
                    <div class="rowElem">
                        <label>{% trans 'Hostname' %}:</label>
                        <div class="formRight">
                            <input type="text" name="hostname" value="{{ server.hostname }}" placeholder="{% trans 'server1.yourserverdomain.com' %}">
                        </div>
                        <div class="fix"></div>
                    </div>
					<div class="rowElem">
                        <label>{% trans 'Slots' %}:</label>
                        <div class="formRight">
                            <input type="text" name="slots" value="{{ server.slots }}" required="required" placeholder="{% trans 'Maximum number of accounts on this server' %}">
                        </div>
                        <div class="fix"></div>
                    </div>
                    <div class="rowElem">
                        <label>{% trans 'Root user' %}:</label>
                        <div class="formRight">
                            <input type="text" name="root_user" required="required" value="{{ server.root_user }}" placeholder="{% trans 'Root username' %}">
                        </div>
                        <div class="fix"></div>
                    </div>
                    
                    <div class="rowElem">
                        <label>{% trans 'Root Password' %}:</label>
                        <div class="formRight">
                            <input type="text" name="root_password" required="required" value="{{ server.root_password }}" placeholder="{% trans 'Root password of the server' %}">
                        </div>
                        <div class="fix"></div>
                    </div>
					<div class="rowElem">
                        <label>{% trans 'YunoHost Admin Password' %}:</label>
                        <div class="formRight">
                            <input type="text" name="admin_password" required="required" value="{{ server.admin_password }}" placeholder="{% trans 'YunoHost admin password of the server' %}">
                        </div>
                        <div class="fix"></div>
                    </div>
					
					<div class="rowElem">
                        <label>{% trans 'Extra config' %}:</label>
                        <div class="formRight">
                            <input type="text" name="config" value="{{ server.config }}" placeholder="{% trans 'extra config' %}">
                        </div>
                        <div class="fix"></div>
                    </div>

                    <div class="rowElem">
                        <label>{% trans 'Enable/Disable' %}:</label>
                            <div class="formRight">
                                <input type="radio" name="active" value="1" {% if server.active %}checked="checked"{% endif %}/><label>{% trans 'Enable' %}</label>
								<input type="radio" name="active" value="0" {% if not server.active %}checked="checked"{% endif %}/><label>{% trans 'Disable' %}</label>
                            </div>
                        <div class="fix"></div>
                    </div>
			<input type="submit" value="{% trans 'Update server' %}" class="greyishBtn submitForm" />
            <input type="button" value="{% trans 'Test connection' %}" class="greyishBtn submitForm" id="test-connection"/>
        </fieldset>

        <input type="hidden" name="server_id" value="{{ server.id }}" />
    </form>

	<form method="post" action="{{ 'api/admin/serviceyunohostshared/change_password'|link }}" class="mainForm save api-form" data-api-msg="{% trans 'YunoHost admin password changed' %}">
        <fieldset>
			<div class="rowElem">
                    <label>{% trans 'Change YunoHost Admin Password' %}:</label>
                    <div class="formRight">
                    <input type="text" name="new_password" required="required" value="{{ server.admin_password }}" placeholder="{% trans 'New YunoHost admin password of the server' %}">
                </div>
                <div class="fix"></div>
            </div>
            <input type="hidden" name="server_id" value="{{ server.id }}" />
            <button class="greyishBtn submitForm" type="submit" value="{% trans 'Change' %}">{% trans 'Change password' %}</button>
        </fieldset>
    </form>
	
	<form method="post" action="{{ 'api/admin/serviceyunohostshared/server_refresh_apps'|link }}" class="api-form" data-api-reload="1">
        <fieldset>
			<div class="rowElem">
                    <label>{% trans 'Apps installed on this server' %}:</label>
                    <div class="formRight">
					<ul>
					{% for path, app in server.apps %}
						<li><a href="https://{{ path }}" target="blank">{{ app }}</a></li>
					{% endfor %}
					</ul>
                </div>
                <div class="fix"></div>
            </div>
            <input type="hidden" name="server_id" value="{{ server.id }}" />
            <button class="greyishBtn submitForm" type="submit" value="{% trans 'Change' %}">{% trans 'Refresh apps' %}</button>
        </fieldset>
    </form>

</div>

{% endblock %}

{% block js%}
<script type="text/javascript">
$(function() {

    $('#test-connection').click(function(){
        $('#server-update').submit();
        bb.post('admin/serviceyunohostshared/server_test_connection', {id:{{server.id}}}, function(result){
            bb.msg('Successfully connected to server');
        });
        return false;
    });

});
</script>

{% endblock %}
